import {chromium,firefox} from 'playwright';
import {readFile,writeFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {resolve,extname,sep} from 'node:path';
const root=resolve('.');
const server=createServer(async(req,res)=>{try{let p=new URL(req.url,'http://localhost').pathname;if(p.endsWith('/'))p+='index.html';const file=resolve('.'+p);if(!file.startsWith(root+sep))throw Error('path');let body=await readFile(file);if(p==='/browser/runtime-worker.js')body=`Error.stackTraceLimit=2000;self.addEventListener('error',e=>postMessage({type:'diagnostic-error',message:e.message,stack:e.error?.stack}));self.addEventListener('unhandledrejection',e=>postMessage({type:'diagnostic-error',message:String(e.reason),stack:e.reason?.stack}));\n`+body;res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.wasm':'application/wasm','.css':'text/css'})[extname(p)]||'application/octet-stream');res.end(body);}catch(e){res.statusCode=404;res.end(String(e));}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const results=[];
try{for(const [engine,rate] of [['chromium',1],['chromium',6],['firefox',1]]){
const b=await({chromium,firefox}[engine]).launch();const p=await b.newPage({viewport:{width:1440,height:1250}});const events=[];const started=Date.now();
await p.exposeFunction('diagRecord',d=>events.push({ms:Date.now()-started,...d}));await p.addInitScript(()=>{const Original=Worker;window.Worker=class extends Original{constructor(...a){super(...a);this.addEventListener('message',e=>diagRecord({frame:location.search,event:e.data}));this.addEventListener('error',e=>diagRecord({frame:location.search,event:{type:'worker-error',message:e.message}}));}postMessage(d,...a){if(d.type==='start')diagRecord({frame:location.search,event:{type:'start',build:d.build,version:d.version}});return super.postMessage(d,...a);}};});
p.on('pageerror',e=>events.push({ms:Date.now()-started,pageerror:e.stack}));if(rate>1){const c=await p.context().newCDPSession(p);await c.send('Emulation.setCPUThrottlingRate',{rate});await c.send('Network.emulateNetworkConditions',{offline:false,latency:100,downloadThroughput:625000,uploadThroughput:125000});}
try{await p.goto(`http://127.0.0.1:${server.address().port}/simulators/`);await p.waitForFunction(()=>[...document.querySelectorAll('.device-status')].every(e=>e.textContent.includes('Running locally')),{},{timeout:95000});
for(let cycle=0;cycle<3;cycle++)for(const name of ['play','schnuartz']){const canvas=p.frameLocator(`[data-device="${name}"] iframe`).locator('#screen');const box=await canvas.boundingBox();for(const [x,y] of [[.94,.03],[.50,.48],[.24,.38],[.5,.95]]){await canvas.click({position:{x:box.width*x,y:box.height*y}});await p.waitForTimeout(300);}}
await p.waitForTimeout(2000);results.push({engine,version:b.version(),rate,events,status:await p.locator('.device-status').allTextContents()});}catch(e){results.push({engine,rate,error:e.message,events,status:await p.locator('.device-status').allTextContents()});}
console.log(engine,rate,results.at(-1).status);await b.close();await writeFile('test-results/diagnosis/gallery.json',JSON.stringify(results,null,2));}}finally{server.close();}
