import { chromium } from 'playwright';
import QRCode from 'qrcode';
import { readFileSync } from 'node:fs';

const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:8765';
const browser = await chromium.launch(process.env.CI ? { headless: true } : { channel: 'chrome', headless: true });
const page = await browser.newPage();
await page.goto(base);

async function decodeQr(text) {
  const image = await QRCode.toDataURL(text, { margin: 4, width: 480 });
  return page.evaluate(async dataUrl => {
    const image = new Image();
    image.src = dataUrl;
    await image.decode();
    const canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx = canvas.getContext('2d');
    ctx.drawImage(image, 0, 0);
    const pixels = ctx.getImageData(0, 0, canvas.width, canvas.height);
    const found = jsQR(pixels.data, pixels.width, pixels.height, { inversionAttempts: 'attemptBoth' });
    ctx.fillStyle = '#fff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    const blank = ctx.getImageData(0, 0, canvas.width, canvas.height);
    const invalid = jsQR(blank.data, blank.width, blank.height);
    return { bytes: found?.binaryData || [], invalid: Boolean(invalid) };
  }, image);
}

async function runSpecterQrProbe(parts) {
  return page.evaluate(async payloads => {
    const { build, version } = await (await fetch('/browser/current.json')).json();
    return new Promise((resolve, reject) => {
      const worker = new Worker('/browser/runtime-worker.js');
      const canvas = new OffscreenCanvas(480, 800);
      const output = [];
      const timer = setTimeout(() => { worker.terminate(); reject(new Error(output.join('\n'))); }, 20000);
      worker.onmessage = ({ data }) => {
        if (data.type === 'log') output.push(data.message);
        if (data.type === 'scanner-state' && data.active) output.push('SCANNER_ACTIVE');
        if (data.type === 'abort' || data.type === 'operation-error') {
          clearTimeout(timer); worker.terminate(); reject(new Error(data.message));
        }
        if (data.type === 'log' && data.message === 'QR_PROBE_READY') {
          for (const part of payloads) {
            const buffer = Uint8Array.from(part).buffer;
            worker.postMessage({ type: 'qr', bytes: buffer }, [buffer]);
          }
        }
        if (data.type === 'log' && data.message.startsWith('QR_PROBE_HEX')) {
          clearTimeout(timer); worker.terminate(); resolve(output);
        }
      };
      worker.onerror = error => { clearTimeout(timer); worker.terminate(); reject(new Error(error.message)); };
      worker.postMessage({ type: 'start', build, version, canvas, qrProbe: true }, [canvas]);
    });
  }, parts);
}

const payload = 'specter browser QR bridge 123';
const decoded = await decodeQr(payload);
if (new TextDecoder().decode(Uint8Array.from(decoded.bytes)) !== payload || decoded.invalid) {
  throw new Error(`QR decoder failed: ${JSON.stringify(decoded)}`);
}
const logs = await runSpecterQrProbe([decoded.bytes]);
const resultHex = logs.find(line => line.startsWith('QR_PROBE_HEX '))?.slice(13);
if (resultHex !== Buffer.from(payload).toString('hex')) {
  throw new Error(`Text QR did not traverse Specter QRHost: ${logs.join('; ')}`);
}
if (!logs.includes('SCANNER_ACTIVE')) throw new Error('Specter QR trigger did not activate browser camera seam');

// Deterministic two-part UR:CRYPTO-PSBT fixture generated by Specter's own
// microur.encoder from b'psbt\xff' + b'test' * 20 with part_len=45.
const urFixture = JSON.parse(readFileSync(new URL("./fixtures/ur-psbt.json", import.meta.url)));
const urParts = urFixture.parts;
const decodedUr = await Promise.all(urParts.map(decodeQr));
for (let i = 0; i < urParts.length; i++) {
  if (new TextDecoder().decode(Uint8Array.from(decodedUr[i].bytes)).toUpperCase() !== urParts[i]) {
    throw new Error(`UR QR fragment ${i + 1} did not decode`);
  }
}
const urLogs = await runSpecterQrProbe(decodedUr.map(part => part.bytes));
const urHex = urLogs.find(line => line.startsWith('QR_PROBE_HEX '))?.slice(13);
const expectedUrHex = urFixture.payloadHex;
if (urHex !== expectedUrHex) {
  throw new Error(`Animated UR/PSBT QR failed in Specter QRHost: ${urLogs.join('; ')}`);
}
console.log(JSON.stringify({ result: 'pass', textQr: payload, invalidQr: 'ignored',
  animatedUrPsbt: 'two QR frames decoded by Specter QRHost' }, null, 2));
await browser.close();
