import React, {forwardRef,useEffect,useRef,useState} from 'react';
import {View,Text,Pressable,StyleSheet} from 'react-native-web';
import {normalizeQr} from './qr-codec';
export const CameraType={Back:'back',Front:'front'};
export const Orientation={PORTRAIT:3,PORTRAIT_UPSIDE_DOWN:1,LANDSCAPE_LEFT:2,LANDSCAPE_RIGHT:4};
export const Camera=forwardRef<any,any>(function BrowserCamera({onReadCode,style,cameraType},ref){
 const video=useRef<HTMLVideoElement>(null), stream=useRef<MediaStream>(), loop=useRef(0), callback=useRef(onReadCode), latest=useRef('');
 const [active,setActive]=useState(false),[direct,setDirect]=useState(false),[message,setMessage]=useState('Choose the camera, a QR image, or Specter DIY.');
 callback.current=onReadCode;
 const stop=()=>{cancelAnimationFrame(loop.current);stream.current?.getTracks().forEach(track=>track.stop());stream.current=undefined;};
 const submit=(result:any)=>{try{const value=normalizeQr(result,true);if(!value||latest.current===value)return;latest.current=value;callback.current?.({nativeEvent:{codeStringValue:value}});}catch(error:any){setMessage(error.message);}};
 useEffect(()=>{const status=(event:Event)=>setMessage((event as CustomEvent).detail);window.addEventListener('blue-qr-status',status);return()=>{stop();window.removeEventListener('blue-qr-status',status);};},[]);
 useEffect(()=>{if(!direct)return;parent.postMessage({type:'blue-scan-state',active:true},location.origin);const onFrame=(event:Event)=>submit({data:(event as CustomEvent).detail});window.addEventListener('blue-qr-frame',onFrame);return()=>{window.removeEventListener('blue-qr-frame',onFrame);parent.postMessage({type:'blue-scan-state',active:false},location.origin);};},[direct]);
 async function start(){stop();setDirect(false);latest.current='';try{stream.current=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:cameraType==='front'?'user':'environment'}}});video.current!.srcObject=stream.current;await video.current!.play();setActive(true);setMessage('Camera active. Scan public test data only.');const canvas=document.createElement('canvas');const tick=()=>{loop.current=requestAnimationFrame(tick);const source=video.current;if(!source||source.readyState<2)return;canvas.width=source.videoWidth;canvas.height=source.videoHeight;const context=canvas.getContext('2d',{willReadFrequently:true})!;context.drawImage(source,0,0);const image=context.getImageData(0,0,canvas.width,canvas.height);const result=(window as any).jsQR(image.data,image.width,image.height,{inversionAttempts:'attemptBoth'});if(result)submit(result);};tick();}catch(error:any){stop();setActive(false);setMessage(error.name==='NotAllowedError'?'Camera access was denied. Use a QR image or Specter DIY.':`Camera unavailable: ${error.message}`);}}
 async function image(){const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const context=canvas.getContext('2d')!;context.drawImage(bitmap,0,0);bitmap.close();const data=context.getImageData(0,0,canvas.width,canvas.height);const result=(window as any).jsQR(data.data,data.width,data.height,{inversionAttempts:'attemptBoth'});if(!result)throw new Error('No readable QR code in this image.');submit(result);}catch(error:any){setMessage(error.message);}};input.click();}
 return <View style={[{flex:1,backgroundColor:'#0b1523',alignItems:'center',justifyContent:'center'},style]}><video ref={video} playsInline muted style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',display:active?'block':'none'}}/><View style={{padding:16,gap:10,zIndex:2,backgroundColor:'#0b1523dd',borderRadius:12}}>{[['Use camera',start],['Scan from Specter DIY',()=>{stop();setActive(false);latest.current='';setDirect(true);setMessage('Waiting for Specter DIY’s visible QR.');}],['Choose QR image',image],...(active?[[ 'Stop camera',()=>{stop();setActive(false);setMessage('Camera stopped.');}]]:[])].map(([label,action]:any)=><Pressable key={label} accessibilityRole="button" onPress={action} style={{padding:12,backgroundColor:'#164875',borderRadius:8}}><Text style={{color:'white',textAlign:'center'}}>{label}</Text></Pressable>)}<Text accessibilityLiveRegion="polite" style={{color:'#cbdef0',maxWidth:260,fontSize:12,textAlign:'center'}}>{message}</Text></View></View>;
});
export async function detectQRCodeInImage(uri:string){const response=await fetch(/^[A-Za-z0-9+/=]+$/.test(uri)?'data:image/png;base64,'+uri:uri);const bitmap=await createImageBitmap(await response.blob());const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const context=canvas.getContext('2d')!;context.drawImage(bitmap,0,0);bitmap.close();const data=context.getImageData(0,0,canvas.width,canvas.height);const result=(window as any).jsQR(data.data,data.width,data.height);return result?normalizeQr(result,true):null;}
