import {noBroadcast} from './policy';
export const hardcodedPeers = [], suggestedServers=[];
export const ELECTRUM_HOST='electrum_host', ELECTRUM_TCP_PORT='electrum_tcp_port', ELECTRUM_SSL_PORT='electrum_ssl_port',ELECTRUM_SERVER_HISTORY='electrum_server_history';
export const ENSURE_CONNECTED_MAX_WALL_MS=0;
export const getConnectionState=()=> 'disabled';
export const subscribeConnectionState=(listener: any)=>{listener('disabled');return ()=>{};};
export const isConnected=()=>false;
export const getPreferredServer=async()=>undefined;
export const removePreferredServer=async()=>{};
export const isDisabled=async()=>true;
export const setDisabled=async()=>{};
export const ensureConnected=async()=>false;
export const presentResetToDefaultsAlert=async()=>false;
export const presentElectrumDisconnectedHelpAlert=async()=>{};
export const getBalanceByAddress=async()=>({confirmed:0,unconfirmed:0});
export const getConfig=async()=>({host:'Offline testnet simulation',connected:false});
export const getSecondsSinceLastRequest=()=>0;
export const getTransactionsByAddress=async()=>[];
export const getMempoolTransactionsByAddress=async()=>[];
export const getTransactionsFullByAddress=async()=>[];
export const ping=async()=>false;
export const multiGetBalanceByAddress=async(addresses:string[])=>({balance:0,unconfirmed_balance:0,addresses:Object.fromEntries(addresses.map(address=>[address,{confirmed:0,unconfirmed:0}]))});
export const multiGetUtxoByAddress=async(addresses:string[])=>Object.fromEntries(addresses.map(address=>[address,[]]));
export const multiGetHistoryByAddress=async(addresses:string[])=>Object.fromEntries(addresses.map(address=>[address,[]]));
export const multiGetTransactionByTxid=async()=>({});
export const calcEstimateFeeFromFeeHistorgam=()=>1;
export const estimateFees=async()=>({fast:1,medium:1,slow:1});
export const estimateFee=async()=>1;
export const serverFeatures=async()=>({genesis_hash:'000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943'});
export const broadcast=noBroadcast, broadcastV2=noBroadcast;
export const estimateCurrentBlockheight=()=>0;
export const calculateBlockTime=()=>0;
export const testConnection=async()=>false;
export const forceDisconnect=()=>{};
export const setBatchingDisabled=()=>{},setBatchingEnabled=()=>{};
export const getServerBanner=async()=> 'Offline Testnet3 simulator — no blockchain connection';
export const getCurrentBlockTip=async()=>0;
export const getConfirmedBlockHeight=async()=>null;
export const getBlockTimestamps=async()=>({});
export const connectMain=async()=>{};
export const waitTillConnected=async()=>false;
