"""Compatibility import for the Playground GUI's unused `import qrcode`.

Both pinned Playground commits import this name but never call it. Specter's
real QR output is generated by its frozen `lvqr` and `qrencoder` modules;
the browser does not replace that rendering or encoding path.
"""
